services:
  # QA Log Sentinel
  - type: web
    name: qa-log-sentinel
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd 'QA Log Sentinel' && pip install -r requirements.txt"
    startCommand: "cd 'QA Log Sentinel' && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # Exterminador de Enlaces Rotos
  - type: web
    name: exterminador-enlaces-rotos
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd 'Exterminador de Enlaces Rotos' && pip install -r requirements.txt"
    startCommand: "cd 'Exterminador de Enlaces Rotos' && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
